### ISSUE TITLE
编译后相对路径出错

### ISSUE THREAD

**Issue by jinxiaodan** [fex-team/fis3-plugin-relative#10]
配置文件：

``` js
fis.match('**', {
  //relative,是制定文件使用相对路径
  relative: true
});
```

源文件：

``` css
body {
    background: url('../css/images/yq-bg04.jpg')
        no-repeat;
}
```

编译后

``` js
body {
    background: url(__relative('/template_html/huifang/css/images/yq-bg04.jpg'))
        no-repeat;
}
```

请教：__relative()是什么鬼00，想保留相对路径怎么弄？
